apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-angular
  template:
    metadata:
      labels:
        app: my-angular
    spec:
      containers:
        - name: my-angular
          image: okteto.dev/my-angular:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: my-angular
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: "my-angular"
      port: 80
  selector:
    app: my-angular
