name: my-angular
services:
  my-angular:
    public: true
    image: okteto.dev/my-angular:latest
    build: .
    replicas: 1
    ports:
      - 3000
    resources:
      cpu: 100m
      memory: 128Mi
