# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mouincmyangularnginx

on:
  push:
    branches:
      - nginx
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: https://mouincnodejs.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_dd5ac53e8e144e628dc4585185bdc415 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_44a62f72a8214b33bc4bd15cc1d70f36 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mouincnodejs.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dd5ac53e8e144e628dc4585185bdc415 }}/myangular-nginx:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "mouincmyangularnginx"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_3ac1c7f499c8454ab5fc7da05e00a194 }}
          images: "mouincnodejs.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dd5ac53e8e144e628dc4585185bdc415 }}/myangular-nginx:${{ github.sha }}"

      # - name: Deploy to Azure Kubernetes Service
      #   id: deploy-to-kubernetes-service
      # - uses: Azure/k8s-deploy@v1.4
      #   with:
      #     namespace: "myangularnginx"
      #     manifests: |
      #       ./kubernetes/deployment.yaml
      #       ./kubernetes/service.yaml
      #     images: "mouincnodejs.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dd5ac53e8e144e628dc4585185bdc415 }}/myangular-nginx:${{ github.sha }}"
      #     imagepullsecrets: |
      #       image-pull-secret1
      #       image-pull-secret2
      #     kubectl-version: "latest"
